# Generated by Django 5.2.9 on 2025-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
