# Generated by Django 5.2.9 on 2025-12-29 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
