# Generated by Django 5.2.9 on 2025-12-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chatmessage_memory_usermemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserMemory',
        ),
    ]
